export const FIRST_NAME_CHANGED = 'FIRST_NAME_CHANGED';
export const LAST_NAME_CHANGED = 'LAST_NAME_CHANGED';
export const USER_NAME_CHANGED = 'USER_NAME_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const ROLE_CHANGED = 'ROLE_CHANGED';
export const REGISTER = 'REGISTER';
export const LOGIN_USERNAME_CHANGED = 'LOGIN_USERNAME_CHANGED';
export const LOGIN_PASSWORD_CHANGED = 'LOGIN_PASSWORD_CHANGED';
export const LOGIN = 'LOGIN';
export const UPDATE = 'UPDATE';
export const LOGIN_ROLE_CHANGED = 'LOGIN_ROLE_CHANGED';
export const PROFILE_FIRST_NAME_CHANGED = 'PROFILE_FIRST_NAME_CHANGED';
export const PROFILE_LAST_NAME_CHANGED = 'PROFILE_LAST_NAME_CHANGED';
export const PROFILE_USER_NAME_CHANGED = 'PROFILE_USER_NAME_CHANGED';
export const PROFILE_PASSWORD_CHANGED = 'PROFILE_PASSWORD_CHANGED';
export const PROFILE_EMAIL_CHANGED = 'PROFILE_EMAIL_CHANGED';
export const PROFILE_PHONE_CHANGED = 'PROFILE_PHONE_CHANGED';
export const FIND_UPDATED_USER = 'FIND_UPDATED_USER';
export const SET_USER = 'SET_USER';
export const FIND_DOCTORS = 'FIND_DOCTORS';
export const FIND_PATIENTS = 'FIND_PATIENTS';
export const DELETE_DOCTOR = 'DELETE_DOCTOR';
export const DELETE_PATIENT = 'DELETE_PATIENT';
export const ADD_DOCTOR = 'ADD_DOCTOR';
export const ADD_PATIENT = 'ADD_PATIENT';
export const FIND_RECORDS = 'FIND_RECORDS';
export const ADMIN_FIRST_NAME_CHANGED = 'ADMIN_FIRST_NAME_CHANGED';
export const ADMIN_LAST_NAME_CHANGED = 'ADMIN_LAST_NAME_CHANGED';
export const ADMIN_USER_NAME_CHANGED = 'ADMIN_USER_NAME_CHANGED';
export const ADMIN_PASSWORD_CHANGED = 'ADMIN_PASSWORD_CHANGED';
export const ADMIN_ROLE_CHANGED = 'ADMIN_ROLE_CHANGED';
export const ADMIN_FIRST_NAME_CHANGED_DOC = 'ADMIN_FIRST_NAME_CHANGED_DOC';
export const ADMIN_LAST_NAME_CHANGED_DOC = 'ADMIN_LAST_NAME_CHANGED_DOC';
export const ADMIN_USER_NAME_CHANGED_DOC = 'ADMIN_USER_NAME_CHANGED_DOC';
export const ADMIN_PASSWORD_CHANGED_DOC = 'ADMIN_PASSWORD_CHANGED_DOC';
export const ADMIN_EMAIL_CHANGED_DOC = 'ADMIN_EMAIL_CHANGED_DOC';
export const ADMIN_PHONE_CHANGED_DOC = 'ADMIN_PHONE_CHANGED_DOC';
export const ADMIN_SPEC_CHANGED_DOC = 'ADMIN_SPEC_CHANGED_DOC';
export const ADMIN_UPDATE_DOC ='ADMIN_UPDATE_DOC';
export const ADMIN_FIND_DOC ='ADMIN_FIND_DOC';
export const ADMIN_FIRST_NAME_CHANGED_PAT = 'ADMIN_FIRST_NAME_CHANGED_PAT';
export const ADMIN_LAST_NAME_CHANGED_PAT = 'ADMIN_LAST_NAME_CHANGED_PAT';
export const ADMIN_USER_NAME_CHANGED_PAT = 'ADMIN_USER_NAME_CHANGED_PAT';
export const ADMIN_PASSWORD_CHANGED_PAT = 'ADMIN_PASSWORD_CHANGED_PAT';
export const ADMIN_EMAIL_CHANGED_PAT = 'ADMIN_EMAIL_CHANGED_PAT';
export const ADMIN_PHONE_CHANGED_PAT = 'ADMIN_PHONE_CHANGED_PAT';
export const ADMIN_AGE_CHANGED_PAT = 'ADMIN_AGE_CHANGED_PAT';
export const ADMIN_GENDER_CHANGED_PAT = 'ADMIN_GENDER_CHANGED_PAT';
export const ADMIN_UPDATE_PAT ='ADMIN_UPDATE_PAT';
export const ADMIN_FIND_PAT ='ADMIN_FIND_PAT';
export const PROFILE_FIRST_NAME_CHANGED_DOC = 'PROFILE_FIRST_NAME_CHANGED_DOC';
export const PROFILE_LAST_NAME_CHANGED_DOC = 'PROFILE_LAST_NAME_CHANGED_DOC';
export const PROFILE_PASSWORD_CHANGED_DOC = 'PROFILE_PASSWORD_CHANGED_DOC';
export const PROFILE_EMAIL_CHANGED_DOC = 'PROFILE_EMAIL_CHANGED_DOC';
export const PROFILE_PHONE_CHANGED_DOC = 'PROFILE_PHONE_CHANGED_DOC';
export const PROFILE_SPEC_CHANGED_DOC = 'PROFILE_SPEC_CHANGED_DOC';
export const FIND_PATIENT_BY_USERNAME = 'FIND_PATIENT_BY_USERNAME';
export const FIND_UPDATED_USER_DOC = 'FIND_UPDATED_USER_DOC';
export const UPDATE_DOC ='UPDATE_DOC';
export const ADMIN_HEIGHT_CHANGED_PAT ='ADMIN_HEIGHT_CHANGED_PAT';
export const ADMIN_WEIGHT_CHANGED_PAT ='ADMIN_WEIGHT_CHANGED_PAT';
export const FIND_MY_DOCTORS ='FIND_MY_DOCTORS';
export const FIND_ALL_MEDICAL_RECORDS ='FIND_ALL_MEDICAL_RECORDS';

export const AppConstants = {
    actions: {
        PROFILE_FIRSTNAME: "PROFILE_FIRSTNAME",
        PROFILE_LASTNAME: "PROFILE_LASTNAME",
        PROFILE_PHONE: "PROFILE_PHONE",
        PROFILE_AGE: "PROFILE_AGE",
        PROFILE_HEIGHT: "PROFILE_HEIGHT",
        PROFILE_WEIGHT: "PROFILE_WEIGHT",
        PROFILE_GENDER: "PROFILE_GENDER",
        PROFILE_EMAIL: "PROFILE_EMAIL",
        PROFILE_PW: 'PROFILE_PW',
        PROFILE_UPDATE: 'PROFILE_UPDATE',
        SET_USER: "SET_USER",
        NAVBAR_SEARCH: "NAVBAR_SEARCH",
        GET_ALL_TRIALS: "GET_ALL_TRIALS",
        SEARCH_TRIALS: "SEARCH_TRIALS",
        GET_TRIAL_BY_ID: "GET_TRIAL_BY_ID",
        ADD_ALLERGY: "ADD_ALLERGY",
        ADD_CONDITION: "ADD_CONDITION",
        ADD_VITAL: "ADD_VITAL",
        ADD_MEDICATION: "ADD_MEDICATION",
        EDIT_ALLERGY: "EDIT_ALLERGY",
        EDIT_CONDITION: "EDIT_CONDITION",
        EDIT_VITAL: "EDIT_VITAL",
        EDIT_MEDICATION: "EDIT_MEDICATION",
        SWITCH_TAB: "SWITCH_TAB",
        CHANGE_ALLERGY_NAME: "CHANGE_ALLERGY_NAME",
        CHANGE_ALLERGEN: "CHANGE_ALLERGEN",
        CHANGE_EFFECT: "CHANGE_EFFECT",
        CHANGE_TREATMENT: "CHANGE_TREATMENT",
        CHANGE_BP: "CHANGE_BP",
        CHANGE_PR: "CHANGE_PR",
        CHANGE_H: "CHANGE_H",
        CHANGE_W: "CHANGE_W",
        CHANGE_BMI: "CHANGE_BMI",
        CHANGE_BT: "CHANGE_BT",
        DELETE_ALLERGY: "DELETE_ALLERGY",
        DELETE_CONDITION: "DELETE_CONDITION",
        DELETE_MEDICATION: "DELETE_MEDICATION",
        UPDATE_ALLERGY: "UPDATE_ALLERGY",
        UPDATE_CONDITION: "UPDATE_CONDITION",
        UPDATE_MEDICATION: "UPDATE_MEDICATION",
        CHANGE_MEDNAME: "CHANGE_MEDNAME",
        CHANGE_CONDITION_NAME: "CHANGE_CONDITION_NAME",
        CHANGE_DIAG_DATE: "CHANGE_DIAG_DATE",
        CHANGE_MEDICATION: "CHANGE_MEDICATION",
        UPDATE_VITALS: "UPDATE_VITALS",
        TOGGLE_BTN_STATE: "TOGGLE_BTN_STATE",
        FIND_ALL_P: "FIND_ALL_P",
        SET_PATIENT: "SET_PATIENT",
        CREATE_M_RECORD: "CREATE_M_RECORD",
        DELETE_M_RECORD: "DELETE_M_RECORD",
        UPDATE_M_RECORD: "UPDATE_M_RECORD",
        FIND_MY_P: "FIND_MY_P",
        RECOMMEND_TRIAL: "RECOMMEND_TRIAL",
        GET_ALL_TRIALS_PATIENT: "GET_ALL_TRIALS_PATIENT",
        FIND_PATIENT_BY_ID: "FIND_PATIENT_BY_ID",
        GET_ALL_TRIALS_DOCTOR: "GET_ALL_TRIALS_DOCTOR",
        RECOMMENDED_TRIALS: "RECOMMENDED_TRIALS"
    },
};