export const FIRST_NAME_CHANGED = 'FIRST_NAME_CHANGED';
export const LAST_NAME_CHANGED = 'LAST_NAME_CHANGED';
export const USER_NAME_CHANGED = 'USER_NAME_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const ROLE_CHANGED = 'ROLE_CHANGED';
export const REGISTER = 'REGISTER';
export const LOGIN_USERNAME_CHANGED = 'LOGIN_USERNAME_CHANGED';
export const LOGIN_PASSWORD_CHANGED='LOGIN_PASSWORD_CHANGED';
export const LOGIN ='LOGIN';
export const UPDATE ='UPDATE';
export const LOGIN_ROLE_CHANGED = 'LOGIN_ROLE_CHANGED';
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PHONE_CHANGED = 'PHONE_CHANGED';
export const FIND_UPDATED_USER = 'FIND_UPDATED_USER';
export const SET_USER = 'SET_USER';
export const AppConstants = {
    actions: {
        NAVBAR_SEARCH: "NAVBAR_SEARCH",
        GET_ALL_TRIALS: "GET_ALL_TRIALS",
        SEARCH_TRIALS: "SEARCH_TRIALS"
    },
};