export const FIRST_NAME_CHANGED = 'FIRST_NAME_CHANGED';
export const LAST_NAME_CHANGED = 'LAST_NAME_CHANGED';
export const USER_NAME_CHANGED = 'USER_NAME_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const ROLE_CHANGED = 'ROLE_CHANGED';
export const REGISTER = 'REGISTER';
export const LOGIN_USERNAME_CHANGED = 'LOGIN_USERNAME_CHANGED';
export const LOGIN_PASSWORD_CHANGED='LOGIN_PASSWORD_CHANGED';
export const LOGIN ='LOGIN';
export const UPDATE ='UPDATE';
export const LOGIN_ROLE_CHANGED = 'LOGIN_ROLE_CHANGED';
export const PROFILE_FIRST_NAME_CHANGED = 'PROFILE_FIRST_NAME_CHANGED';
export const PROFILE_LAST_NAME_CHANGED = 'PROFILE_LAST_NAME_CHANGED';
export const PROFILE_USER_NAME_CHANGED = 'PROFILE_USER_NAME_CHANGED';
export const PROFILE_PASSWORD_CHANGED = 'PROFILE_PASSWORD_CHANGED';
export const PROFILE_EMAIL_CHANGED = 'PROFILE_EMAIL_CHANGED';
export const PROFILE_PHONE_CHANGED = 'PROFILE_PHONE_CHANGED';
export const FIND_UPDATED_USER = 'FIND_UPDATED_USER';
export const SET_USER = 'SET_USER';
export const FIND_DOCTORS = 'FIND_DOCTORS';
export const FIND_PATIENTS = 'FIND_PATIENTS';
export const DELETE_DOCTOR = 'DELETE_DOCTOR';
export const DELETE_PATIENT = 'DELETE_PATIENT';
export const ADD_DOCTOR = 'ADD_DOCTOR';
export const ADD_PATIENT = 'ADD_PATIENT';
export const FIND_RECORDS = 'FIND_RECORDS';
export const ADMIN_FIRST_NAME_CHANGED = 'ADMIN_FIRST_NAME_CHANGED';
export const ADMIN_LAST_NAME_CHANGED = 'ADMIN_LAST_NAME_CHANGED';
export const ADMIN_USER_NAME_CHANGED = 'ADMIN_USER_NAME_CHANGED';
export const ADMIN_PASSWORD_CHANGED = 'ADMIN_PASSWORD_CHANGED';
export const ADMIN_ROLE_CHANGED = 'ADMIN_ROLE_CHANGED';

export const AppConstants = {
    actions: {
        NAVBAR_SEARCH: "NAVBAR_SEARCH",
        GET_ALL_TRIALS: "GET_ALL_TRIALS",
        SEARCH_TRIALS: "SEARCH_TRIALS"
    },
};